Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 100

Style/ParallelAssignment:
  Enabled: false

Style/StructInheritance:
  Enabled: false

AllCops:
  Exclude:
    - 'mines_field.gemspec'
